### ISSUE TITLE
IMU and Odom Coordination

### ISSUE THREAD

**Issue by hoangvietdo** [incsl/airsim_stereo_recording#1]
Before rotating Odom data 180 degree around x-axis (roll angle):
- Only using stereo camera
![only-stereo-camera](https://user-images.githubusercontent.com/51826956/185105847-a6fe4a6c-24d3-4f79-9b57-fce827f9f61f.png)

- Stereo camera + IMU
![stereo_imu](https://user-images.githubusercontent.com/51826956/185105808-b8c0608e-dbc7-439d-9d4b-ac3269fa9d93.png)

First, I thought Odom data has some problems but after reverting and checking again followed with these results, the problem is probably from IMU data. Can you give me some thoughts @lastflowers?

**Comment by hoangvietdo** [comment]
After flipping the Odom:
- Stereo camera + IMU
![after_flipped](https://user-images.githubusercontent.com/51826956/185107100-f20d9806-68fa-410c-9cd0-7efc2d21befd.png)

**Comment by hoangvietdo** [comment]
After checking with the drone dataset, I think I find the answer to this problem. Let have a look at these results @lastflowers:
- z-axis of Stereo only (Left: VINS-Fusion, Right: Ground Truth)
![stereo_only_drone](https://user-images.githubusercontent.com/51826956/185141071-f11bbb76-148e-4c49-bedb-2cb63fa98638.png)

- z-axis of Stereo + IMU (Left: VINS-Fusion, Right: Ground Truth)
![stereo_imu_drone](https://user-images.githubusercontent.com/51826956/185141133-30ff2e07-b763-4c90-815b-d4da0c129c4d.png)

We can see that, VINS-Fusion outputs the odom of stereo-only in NED, but for stereo-imu, the frame is ENU-like (from the above comment result, only y and z are flipped 180 degrees, x is kept the same, so not actually ENU). This is really weird.

**Comment by hoangvietdo** [comment]
I got exactly same problem when running dataset with open-vins (see new commit ac8f949534f5a095a7401127658c1c0a378bc06a).
Is it because of the dataset or because of characteristics of VINS algorithms (related to camera coordinate)? Can you confirm @lastflowers?

**Comment by lastflowers** [comment]
Hi.

I guess it is because of the definition of the global (reference frame). In robotics community, it is common to define the z-axis as the inverse direction of gravity (ENU-like). But in our case, we define the z-axis as the gravity direction (NED-like).

One thing I would like to note is that, for vins-fusion with only stereo, the definition of the global frame is the first body frame. Since you set the body frame as a virtual IMU, the global frame was set as NED-like frame.

**Comment by hoangvietdo** [comment]
@lastflowers Ok I see, so basically IMU frame = forward-right-down, global frame = foward-left-up. This means NED frame in Airsim is actually FRD. Is it correct?

**Comment by lastflowers** [comment]
Yes, you are right. Since we do not know the north direction, the x-axis of the global frame is aligned with the first x-axis of IMU frame.

**Comment by hoangvietdo** [comment]
Ok thanks. Everything is clear to me now.
